### ISSUE TITLE
Resulting zip files seem to contain _everything_

### ISSUE THREAD

**Issue by davidfox-ap** [ubaniabalogun/serverless-package-python-functions#13]
Thank you again for your help with my previous issue -- I can only hope you'll be as accommodating with this one. :-)

I have set up my functions as suggested in your documentation:
```
  stage4ingestion:
    handler: stage4ingestion-handler.stage4ingestion
    environment:
      S3PREFIX: ${file(./serverless.env.yml):${opt:stage}.S3PREFIX}
    package:
      include:
        - stage4ingestion
      artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:service}-${opt:stage}-stage4ingestion.zip
```

But when I look inside the resulting zip file:

.serverless/stage4ingestion.zip

I see it contains not only the files that were inside the ./stage4ingestion folder, but all of the files and folders at root level -- including the _build directory.

I did not notice this until I had several functions in my deployment and I began seeing 'Array buffer allocation failed' error messages due to file size limitations with Lambda.

Maybe there's something I missed regarding including/excluding files?
